%%{init: {'theme':'dark', 'themeVariables': { 'primaryColor':'#1168bd'}}}%%
C4Context
    title System Context - jobs

    Person(user, "System User", "Interacts with the system")

    System(main_system, "jobs", "")


    
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="2")
