%%{init: {'theme':'dark', 'themeVariables': { 'primaryColor':'#1168bd'}}}%%
C4Container
    title Container Diagram - jobs Architecture

    Person(user, "System User", "Application user")

    Container_Boundary(system_boundary, "jobs") {
    }

    UpdateLayoutConfig($c4ShapeInRow="2", $c4BoundaryInRow="1")
